# Nombre de la aplicación
quarkus.application.name=backend-citas-fhir

# Configuración de Conexión a MongoDB Atlas (Nube)
quarkus.mongodb.connection-string=mongodb+srv://admin_citas:12345@cluster0.qp3c9nv.mongodb.net/citas_db?retryWrites=true&w=majority
quarkus.mongodb.database=citas_db

# Habilitar CORS para recibir peticiones desde el frontend en React (Local y Producción)
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS

# Niveles de Log
quarkus.log.category."org.acme".level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3}] (%t) %s%e%n